Feat/#29
JANGJEEYEON/meet_FE pull request #35
Opened 2024-06-30 13:58 UTC by JANGJEEYEON

### 변경 사항
투표 전, 후 페이지 개발했습니다.

### 테스트 결과
![스크린샷 2024-06-30 225646](https://github.com/JANGJEEYEON/meet_FE/assets/106160603/c0dbd63e-59cb-46d8-88d4-ba7a64e80675)
![스크린샷 2024-06-30 225713](https://github.com/JANGJEEYEON/meet_FE/assets/106160603/009aa75a-b13d-4623-b9c3-fb4e848b7a80)

2024-06-30 15:30 UTC, jomulagy requested changes
잘하긴 했는데 ui가 이게 최선인가요..? ㅋㅋ

2024-06-30 15:30 UTC, jomulagy commented on src/components/ScheduleVoteBefore.tsx
> +          />
기존에 존재하는 투표 항목은 입력을 위한 필드가 아니기 때문에, input 태그는 적절하지 않은 것 같습니다.

2024-06-30 15:30 UTC, jomulagy commented on src/components/ScheduleVoteBefore.tsx
> +  const handleAddSchedule = () => {
추가하기 버튼을 눌렀을떄, input 태그가 나타나는 것이 더 자연스러울 것 같습니다.

2024-06-30 15:30 UTC, jomulagy commented on src/components/ScheduleVoteBefore.tsx
> +          >
삭제 가능 여부를 확인후, 삭제하기 버튼이 표시되어야 할 것 같습니다.

2024-06-30 15:30 UTC, jomulagy commented on src/components/ScheduleVoteAfter.tsx
> +  const schedule = "";
투표 항목, 투표한 사람의 정보를 담을 component가 없나요?

2024-06-30 15:30 UTC, jomulagy commented on src/components/ScheduleVoteBefore.tsx
> +        <div key={index} className="flex items-center mb-4">
사용자가 이전에 투표를 했는지 안했는지, 표시 하는 부분이 빠졌습니다.

2024-07-06 06:28 UTC, jomulagy reviewed
투표 항목은 안받아오나요?

2024-07-06 06:28 UTC, jomulagy commented on src/components/ScheduleVoteBefore.tsx
> +            userId: currentUserId,
userId는 안보내도 됩니다. swagger 수정 했습니다

2024-07-06 06:28 UTC, jomulagy commented on src/components/ScheduleVoteBefore.tsx
> +          id: `${schedules.length + 1}`,
id는 백엔드에서 내려주는 값을 써야 합니다.

2024-07-06 06:28 UTC, jomulagy commented on src/components/ScheduleVoteBefore.tsx
> +          userId: currentUserId,
userID 대신 editable 추가했습니다. editable이 true 면 수정가능, false 면 수정 불가로 변경 부탁해요

2024-07-06 06:28 UTC, jomulagy commented on src/pages/ScheduleVotePage.tsx
> +  };
맞는지 확인해주세요

2024-07-07 15:51 UTC, yujin5959 reviewed
전체적으로 코드 읽어봤는데 좀 더 문법 적으로 이해해보겠습니다

2024-07-07 16:21 UTC, JANGJEEYEON commented
전체적으로 코드 읽어봤습니다 몇 번 더 읽고 제대로 이해하겠습니다

2024-07-08 12:35 UTC, jomulagy approved these changes

2024-07-11 11:25 UTC, yujin5959 approved these changes
코드 리뷰 빠르게 하겠습니다 ㅜㅜㅜ 죄송합니다...

2024-07-11 11:29 UTC, merged