Feat: 모임 detail 페이지 수정
JANGJEEYEON/meet_FE pull request #41
Opened 2024-07-08 07:05 UTC by JANGJEEYEON

### 변경 사항
type 만들었습니다.

### 테스트 결과

2024-07-08 12:31 UTC, jomulagy requested changes
detail page는 url에 id 가 있어야 됩니다. 수정 부탁해요

2024-07-08 12:31 UTC, jomulagy commented on src/pages/MeetDetail.tsx
> +};
dummy data 를 사용하여 테스트 한 부분이 좋네요

2024-07-08 12:35 UTC, jomulagy approved these changes

2024-07-08 12:35 UTC, jomulagy commented on src/pages/MeetDetail.tsx
> +
dummy data를 사용하여 잘 테스트 하셨네요

2024-07-11 11:25 UTC, yujin5959 approved these changes
Approve 함미다!!!!!!!

2024-07-11 13:47 UTC, jomulagy commented on src/pages/MeetDetail.tsx
> +  }
위의 조건문은 url parameter의 id와 api로 받아온 data의 id를 검증하는 로직 인것 같고
아래는 data가 없을때의 화면 인 것 같습니다.

2024-07-15 08:37 UTC, merged