feat : 장소 투표 페이지 개발
JANGJEEYEON/meet_FE pull request #43
Opened 2024-07-13 16:48 UTC by JANGJEEYEON

### 변경 사항
장소 투표 페이지 개발했습니다.

### 테스트 결과

https://github.com/user-attachments/assets/e6136c79-2f1a-44c3-92e9-96e5dd4ac646

2024-07-14 03:05 UTC, jomulagy requested changes

2024-07-14 03:05 UTC, jomulagy commented on src/components/PlaceVoteAfter.tsx
> +          </span>
투표 완료 여부가 아니라 투표수, 투표한 사람이 나와야 됩니다

2024-07-14 03:05 UTC, jomulagy commented on src/components/PlaceVoteAfter.tsx
> +};
지난 주에 말했듯이, 여러 파일에서 사용하는 타입은 타입 분리가 필요합니다.

2024-07-14 03:05 UTC, jomulagy commented on src/components/PlaceVoteBefore.tsx
> +    updatePlaceList(updatedPlaces);
places 와 updatedPlaceList는 무슨 차이가 있나요?

2024-07-14 03:05 UTC, jomulagy commented on src/pages/PlaceVotePage.tsx
> +};
meet  타입은 이미 정의 되어 있습니다. pr 확인해주세요

2024-08-09 07:23 UTC, JANGJEEYEON commented on src/components/PlaceVoteAfter.tsx
> +          </span>
코드 수정했습니다

2024-08-09 07:30 UTC, JANGJEEYEON commented on src/components/PlaceVoteBefore.tsx
> +    updatePlaceList(updatedPlaces);
setPlaces(updatedPlaces)는 현재 컴포넌트 안에 있는 places 상태를 업데이트하고, updatePlaceList(updatedPlaces)는 부모 컴포넌트에 있는 placeList 상태를 업데이트합니당

2024-08-09 07:40 UTC, jomulagy commented on src/components/PlaceVoteAfter.tsx
> +          </span>
동영상에 반영이 안되 있는거 같은데, 코드로 확인했습니다. 고생 하셨습니다.

2024-08-09 07:41 UTC, jomulagy commented on src/components/PlaceVoteBefore.tsx
> +    updatePlaceList(updatedPlaces);
부모 컴포넌트의 setter를 사용하는 것이 설계상 적절해 보입니다. 현재 이슈는 화면 개발이기 떄문에 추후 기능 개발 이슈에서 반영해주세요

2024-08-09 07:41 UTC, jomulagy approved these changes

2024-08-09 09:01 UTC, yujin5959 approved these changes

2024-08-09 10:49 UTC, merged