feat: 모임 게시판(list) 기능 개발
JANGJEEYEON/meet_FE pull request #49
Opened 2024-08-11 07:46 UTC by yujin5959

### 변경 사항
- 모임 게시판(list) 전체 조회
- 페이지 네이션 기능 추가로 넘어가면서 확인 가능 
- 각 탭을 누르면 pathvariable 잘 받아와서 상세 페이지로 넘어갈 수 있도록 구현 완료

### 테스트 결과
<img width="330" alt="스크린샷 2024-08-11 오후 4 45 50" src="https://github.com/user-attachments/assets/254e6c93-bfa7-41b6-9fce-f09c9bab64d5">

2024-08-11 09:29 UTC, jomulagy requested changes

2024-08-11 09:29 UTC, jomulagy commented on src/pages/MeetList.tsx
> +      }
공통 API를 사용하도록 변경해 주세요

2024-08-11 09:29 UTC, jomulagy commented on src/pages/MeetList.tsx
> +      </nav>
모든 페이지에 공통으로 사용 할 수 있도록 변경해주세요

2024-08-11 09:29 UTC, jomulagy commented on src/pages/MeetList.tsx
> +      </div>
좋은 생각이지만 APP에서는 페이지 네이션을 누르기 힘들기 때문에, 무한 스크롤로 구현하는게 좋을 것 같습니다.

2024-08-11 09:29 UTC, jomulagy commented on src/pages/MeetList.tsx
> +  }
에러 발생시에는 에러 페이지로 이동하게 되어 있습니다.

2024-08-11 09:29 UTC, jomulagy commented on src/pages/MeetList.tsx
> +  };
페이지가 바뀌면 meetList를 업데이트 해야 하지 않나요?

2024-08-11 15:41 UTC, yujin5959 commented on src/pages/MeetList.tsx
> +  };
페이지네이션이라 현재 페이지 상태만 업데이트 하는식으로 meetList를 업데이트 하는게 아니고 페이지 번호? 누를 때마다 호출해서 페이지 마다 meetlist 일부 보이게? 한거예요

2024-08-11 15:55 UTC, yujin5959 commented on src/pages/MeetList.tsx
> +  }
넵넵

2024-08-11 15:55 UTC, yujin5959 commented on src/pages/MeetList.tsx
> +      </div>
넵넵

2024-08-11 16:00 UTC, yujin5959 commented on src/pages/MeetList.tsx
> +      </nav>
넴넴

2024-08-11 16:02 UTC, yujin5959 commented on src/pages/MeetList.tsx
> +  };
스크롤로 바꿔서 필요없을 것 같습니다!!!

2024-08-11 16:43 UTC, yujin5959 commented
FooterNav.tsx 올리는 거 깜빡해서 추가로 올릴게요

2024-08-13 05:40 UTC, JANGJEEYEON approved these changes

2024-08-13 17:27 UTC, jomulagy approved these changes
무한스크롤은 아니지만 현재 스펙에서는 문제 없을 것 같습니다. 추후에 도전해 보는걸로..

https://velog.io/@somda/FE-React%EB%A1%9C-%EB%AC%B4%ED%95%9C-%EC%8A%A4%ED%81%AC%EB%A1%A4%EC%9D%84-%EA%B5%AC%ED%98%84%ED%95%B4%EB%B3%B4%EC%9E%90

2024-08-14 04:05 UTC, merged