feat: 모임 detail 기능 개발
JANGJEEYEON/meet_FE pull request #67
Opened 2024-08-26 14:42 UTC by yujin5959

### 변경 사항
- 컨벤션 참고 에러시 에러 페이지로 이동하기로 공통 api 수정 완료 (delete, get)
- issue #31에 해당하는 파일 재 PR 
- 공통 디자인 적용 하지 않음 

### 테스트 결과
<img width="592" alt="image" src="https://github.com/user-attachments/assets/a374a54c-e7be-4934-853f-ce9eba3718b0">

2024-08-27 15:48 UTC, jomulagy requested changes

2024-08-27 15:48 UTC, jomulagy commented on src/pages/MeetDetail.tsx
> +          alert("모임이 삭제되었습니다.");
alert는 사용을 지양하고 있습니다. 삭제 부탁드립니다.

2024-08-27 15:48 UTC, jomulagy commented on src/pages/MeetDetail.tsx
> +          navigate("/not-found"); // 오류 발생 시 에러 페이지로 이동
not found는 404의 경우 입니다.

2024-08-27 15:48 UTC, jomulagy commented on src/pages/MeetDetail.tsx
> +  }
에러 컨벤션 위배입니다

2024-08-27 15:48 UTC, jomulagy commented on src/pages/MeetDetail.tsx
> +    return <div className="text-center py-8">모임 정보가 없습니다.</div>;
에러 컨벤션 위배 입니다.

2024-08-27 15:48 UTC, jomulagy commented on src/pages/MeetDetail.tsx
> +      navigate(`/edit/${meetInfo.id}`);
url 확인해주세요

2024-08-27 15:48 UTC, jomulagy commented on src/pages/MeetDetail.tsx
> +            console.log("API response:", response.data);
개발중에 사용한 console은 삭제해주세요

2024-08-27 16:57 UTC, JANGJEEYEON approved these changes
에러 컨벤션과 동작 확인했습니다!

2024-08-29 14:39 UTC, jomulagy approved these changes

2024-08-29 14:40 UTC, merged